version: '3.8'

services:
  db:
    image: mysql:5.5.60
    container_name: ttc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ttc_aalst
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "7202:3306"
    networks:
      - ttcnet
    volumes:
      - mysql-data:/var/lib/mysql

  ttc-webapi:
    build:
      context: ./
      dockerfile: ./src/Ttc.WebApi/Dockerfile
    container_name: ttc-backend
    restart: always
    ports:
      - "7200:8080"
    networks:
      - ttcnet
      - monitoring_monitoring
      - pongrank_pongranknet
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MAILKIT_PASSWORD=${MAILKIT_PASSWORD}
    volumes:
      - ./upload:/upload
      - /volume1/Projects/Erembodegem-Logs:/app/logs
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  ttcnet:
    driver: bridge
  monitoring_monitoring:
    external: true
  pongrank_pongranknet:
    external: true
