version: '3.8'

services:
  db:
    image: mysql:5.5.60
    container_name: ttc-mysql-migrations
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ttc_aalst
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "7202:3306"
    networks:
      - ttcnet
    volumes:
      - mysql-data:/var/lib/mysql

  webapi:
    build:
      context: ./
      dockerfile: ./src/Ttc.WebApi/Dockerfile
    container_name: ttc-backend-migrations
    restart: always
    ports:
      - "7200:8080"
    networks:
      - ttcnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./upload:/upload
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  ttcnet:
    driver: bridge
