version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: ttc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ttc_aalst
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "7202:3306"
    networks:
      - ttcnet
    volumes:
      # TODO: this didn't seem to be working on Synology...
      - ./db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  webapi:
    build:
      context: ./
      dockerfile: ./src/Ttc.WebApi/Dockerfile
    container_name: ttc-backend
    restart: always
    ports:
      - "7200:8080"
      - "7201:4003"
    networks:
      - ttcnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:4003;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=stockoma
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ./upload:/upload
      - ./https:/https
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  ttcnet:
    driver: bridge
